#spring:
#  application:
#    name: config-server
#  profiles:
#    active: native #, git, vault
#
#  cloud:
#    config:
#      server:
#        encrypt.enabled: false
#        native:
#          search-locations: classpath:/config
#
#
#
#server:
#  port: 8071


#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"
